git:
  depth: 1
language: node_js
node_js:
  - '16'
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
  override:
    - yarn install --immutable --immutable-cache --check-cache
install:
  - yarn install
script:
  - yarn lerna run build
  - yarn lerna run ci
